name: Static Checks

on: [push, pull_request]

jobs:
  static-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint bandit safety
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        pylint src/classification_binary.py

    - name: Run bandit
      run: |
        bandit -r src

    - name: Run safety
      run: |
        safety scan --key=$SAFETY_API_KEY
